import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const poppinsClassName: string = poppins.className;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsClassName}  bg-[#FAFAFA] antialiased`}>
        {children}
        <Toaster
          expand
          position="top-right"
          toastOptions={{
            style: {
              background: "#60E5AE",
              color: "#000000",
              border: "none",
            },
          }}
        />
      </body>
    </html>
  );
}
